# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael's Musings
email: michaelong8198@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A music student's journey through the great works of the past, and maybe the present.
baseurl: "/life" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://moke8198.github.io" # the base hostname & protocol for your site
twitter_username: lolilolicon_
github_username:  moke8198
disqus_username:
audio_file: "/audio/test2.mp3"
audio_title: "Mendelssohn Violin Concerto in E Minor"

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: true
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
